# Generated by Django 5.1 on 2024-08-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indumentaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='camiseta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='short',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
